package com.dsanti.dcode.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF646100)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFECE76D)
val md_theme_light_onPrimaryContainer = Color(0xFF1E1D00)
val md_theme_light_secondary = Color(0xFF616042)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8E4BE)
val md_theme_light_onSecondaryContainer = Color(0xFF1D1C05)
val md_theme_light_tertiary = Color(0xFF3E6655)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC0ECD7)
val md_theme_light_onTertiaryContainer = Color(0xFF002116)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1C16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1C16)
val md_theme_light_surfaceVariant = Color(0xFFE7E3D1)
val md_theme_light_onSurfaceVariant = Color(0xFF49473A)
val md_theme_light_outline = Color(0xFF7A7768)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0E7)
val md_theme_light_inverseSurface = Color(0xFF31302B)
val md_theme_light_inversePrimary = Color(0xFFD0CB54)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF646100)
val md_theme_light_outlineVariant = Color(0xFFCAC7B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD0CB54)
val md_theme_dark_onPrimary = Color(0xFF343200)
val md_theme_dark_primaryContainer = Color(0xFF4B4900)
val md_theme_dark_onPrimaryContainer = Color(0xFFECE76D)
val md_theme_dark_secondary = Color(0xFFCBC8A4)
val md_theme_dark_onSecondary = Color(0xFF333118)
val md_theme_dark_secondaryContainer = Color(0xFF49482C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8E4BE)
val md_theme_dark_tertiary = Color(0xFFA5D0BB)
val md_theme_dark_onTertiary = Color(0xFF0D3729)
val md_theme_dark_tertiaryContainer = Color(0xFF264E3E)
val md_theme_dark_onTertiaryContainer = Color(0xFFC0ECD7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1C16)
val md_theme_dark_onBackground = Color(0xFFE6E2D9)
val md_theme_dark_surface = Color(0xFF1C1C16)
val md_theme_dark_onSurface = Color(0xFFE6E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF49473A)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC7B5)
val md_theme_dark_outline = Color(0xFF949181)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C16)
val md_theme_dark_inverseSurface = Color(0xFFE6E2D9)
val md_theme_dark_inversePrimary = Color(0xFF646100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD0CB54)
val md_theme_dark_outlineVariant = Color(0xFF49473A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF646100)

val error = Color(0xFFB3261E)