package com.dsanti.buildsrc

internal object Versions {
    const val compose = "1.6.7"
    const val activityCompose = "1.9.0"
    const val pagingCompose = "3.3.0"
    const val navCompose = "2.7.7"
    const val constraintLayoutCompose = "1.1.0-alpha12"
    const val coilCompose = "2.6.0"
    const val kotlin = "1.9.24"
    const val coroutines = "1.7.1"
    const val androidLifecycleGrouped = "2.8.1"
    const val paging = "3.3.0"
    const val room = "2.6.0-alpha03"
    const val coreKtx = "1.13.1"
    const val appcompat = "1.7.0-alpha03"
    const val paletteKtx = "1.0.0"
    const val material = "1.6.0" 
    const val material3 = "1.2.1"
    const val playServicesAds = "23.1.0"
    const val gson = "2.10.1"
    const val multidex = "2.0.1"
    const val junitJupiterApi = "5.9.3"
    const val junitJupiterEngine = "5.9.3"
    const val truth = "1.1.3"
    const val androidXJunit = "1.1.5"
    const val biometric = "1.2.0-alpha05"
    const val googleFonts = "1.4.0-alpha04"
    const val ktor = "2.3.1"
    const val koin = "3.4.3"
    const val aboutLibs = "10.6.1"
    const val firebaseBOM = "32.1.1"
    const val dataStore = "1.1.0-alpha02"
    const val accompanist = "0.35.1-alpha"
    const val cameraX = "1.3.0-rc01"
    const val zxing = "4.3.0"
    const val zxingGoogle = "3.5.0"
    const val fontAwesome = "1.1.0"
    const val cropImager = "4.2.1"
    const val capturable = "1.0.3"
}