package com.dsanti.buildsrc

internal object Versions {
    const val compose = "1.2.1"
    const val composeCompiler = "1.3.0"
    const val activityCompose = "1.5.1"
    const val pagingCompose = "1.0.0-alpha16"
    const val navCompose = "2.5.1"
    const val constraintLayoutCompose = "1.0.1"
    const val coilCompose = "2.2.2"
    const val kotlin = "1.7.10"
    const val coroutines = "1.5.1"
    const val androidLifecycleGrouped = "2.5.1"
    const val paging = "3.2.0-alpha02"
    const val room = "2.4.3"
    const val coreKtx = "1.8.0"
    const val appcompat = "1.5.0"
    const val paletteKtx = "1.0.0"
    const val material = "1.6.0"
    const val material3 = "1.0.0-alpha16"
    const val playServicesAds = "22.0.0"
    const val gson = "2.8.7"
    const val multidex = "2.0.1"
    const val junitJupiterApi = "5.7.0"
    const val junitJupiterEngine = "5.7.0"
    const val truth = "1.1.3"
    const val androidXJunit = "1.1.3"
    const val biometric = "1.2.0-alpha03"
    const val googleFonts = "1.4.0-alpha04"
    const val ktor = "2.2.2"
    const val koin = "3.3.2"
    const val aboutLibs = "10.5.2"
    const val firebaseBOM = "30.0.2"
    const val dataStore = "1.0.0"
    const val accompanist = "0.24.7-alpha"
    const val cameraX = "1.1.0-beta03"
    const val zxing = "4.3.0"
    const val zxingGoogle = "3.5.0"
    const val fontAwesome = "1.1.0"
    const val cropImager = "4.2.1"
    const val capturable = "1.0.3"
}